---
- name: Create a volume
  docker_volume:
    name: "{{docker_volume}}"
        
- name: Create a network
  docker_network:
    name: "{{docker_network}}"
    state: present

- name: "Launch database container"
  docker_container:
    name: "{{ db_name }}"
    image: mysql:5.7
    volumes:
      - "{{ docker_volume }}:/var/lib/mysql:rw"
    restart_policy: always
    network_mode: wordpress_net
    env:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

- name: "Launch wordpress container"
  docker_container:
    name: "{{ wp_name }}"
    image: wordpress:latest
    ports:
      - 8080:80
    restart_policy: always
    network_mode: wordpress_net
    env:
      WORDPRESS_DB_HOST: "{{ db_name }}:3306"
      WORDPRESS_DB_PASSWORD: wordpress
